# Generated by Django 4.2.5 on 2023-10-08 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Date_created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=datetime.datetime.now),
        ),
    ]
