# Generated by Django 4.2.5 on 2023-10-08 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_task_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
